export const AppErrorCode = {
  // Standard HTTP error codes
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Domain security error codes
  CLEARANCE_INSUFFICIENT: 'CLEARANCE_INSUFFICIENT',
  GRANT_EXPIRED: 'GRANT_EXPIRED',
  GRANT_REVOKED: 'GRANT_REVOKED',
  DOCUMENT_NOT_DISCOVERABLE: 'DOCUMENT_NOT_DISCOVERABLE',
  MALWARE_DETECTED: 'MALWARE_DETECTED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  SESSION_TERMINATED: 'SESSION_TERMINATED',
  AUDIT_MUTATION_FORBIDDEN: 'AUDIT_MUTATION_FORBIDDEN',
  WATERMARK_GENERATION_FAILED: 'WATERMARK_GENERATION_FAILED',
  POLICY_DENIED: 'POLICY_DENIED',
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];
