export const AppErrorCode = {
  // Standard HTTP error codes
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Domain security error codes
  CLEARANCE_INSUFFICIENT: 'CLEARANCE_INSUFFICIENT',
  GRANT_EXPIRED: 'GRANT_EXPIRED',
  GRANT_REVOKED: 'GRANT_REVOKED',
  DOCUMENT_NOT_DISCOVERABLE: 'DOCUMENT_NOT_DISCOVERABLE',
  MALWARE_DETECTED: 'MALWARE_DETECTED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  SESSION_TERMINATED: 'SESSION_TERMINATED',
  AUDIT_MUTATION_FORBIDDEN: 'AUDIT_MUTATION_FORBIDDEN',
  WATERMARK_GENERATION_FAILED: 'WATERMARK_GENERATION_FAILED',
  POLICY_DENIED: 'POLICY_DENIED',

  // Document Lifecycle error codes
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_ALREADY_ACTIVE: 'DOCUMENT_ALREADY_ACTIVE',
  DOCUMENT_ARCHIVED: 'DOCUMENT_ARCHIVED',
  DOCUMENT_ACTIVATION_FAILED: 'DOCUMENT_ACTIVATION_FAILED',
  VERSION_NOT_CLEAN: 'VERSION_NOT_CLEAN',
  VERSION_NOT_FOUND: 'VERSION_NOT_FOUND',
  INVALID_VERSION_TARGET: 'INVALID_VERSION_TARGET',
  RETENTION_DATE_INVALID: 'RETENTION_DATE_INVALID',
  TECHNICAL_ADMIN_CANNOT_OWN: 'TECHNICAL_ADMIN_CANNOT_OWN',
  DOCUMENT_ACCESS_DENIED: 'DOCUMENT_ACCESS_DENIED',

  // Document Search error codes
  SEARCH_QUERY_TOO_LONG: 'SEARCH_QUERY_TOO_LONG',
  SEARCH_QUERY_INVALID: 'SEARCH_QUERY_INVALID',

  // Access Grant error codes
  GRANT_NOT_FOUND: 'GRANT_NOT_FOUND',
  GRANT_ALREADY_REVOKED: 'GRANT_ALREADY_REVOKED',
  GRANT_OVERLAP_EXISTS: 'GRANT_OVERLAP_EXISTS',
  GRANT_PRINCIPAL_INVALID: 'GRANT_PRINCIPAL_INVALID',
  GRANT_DOWNLOAD_FORBIDDEN: 'GRANT_DOWNLOAD_FORBIDDEN',
  GRANT_CLEARANCE_INSUFFICIENT: 'GRANT_CLEARANCE_INSUFFICIENT',
  GRANT_ABAC_DENIED: 'GRANT_ABAC_DENIED',
  GRANT_CONCURRENCY_CONFLICT: 'GRANT_CONCURRENCY_CONFLICT',
  GRANT_DURATION_EXCEEDED: 'GRANT_DURATION_EXCEEDED',
  GRANT_TIME_RANGE_INVALID: 'GRANT_TIME_RANGE_INVALID',
  USER_NOT_ACTIVE: 'USER_NOT_ACTIVE',
  ROLE_NOT_ACTIVE: 'ROLE_NOT_ACTIVE',
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];
